@USER=danny
@EMAIL=danny@example.com
@PASSWORD=pass123

@LOGIN_USER = {{USER}}
@LOGIN_PASSWORD = {{PASSWORD}}
#@LOGIN_USER = admin
#@LOGIN_PASSWORD = test123

### GET request to example server

POST {{host}}/api/auth/register
Content-Type: application/json

{
    "username": "{{USER}}",
    "email": "{{EMAIL}}",
    "password": "{{PASSWORD}}"
}

### GET request to example server

POST {{host}}/api/auth/login
Content-Type: application/json

{
    "username": "{{LOGIN_USER}}",
    "password": "{{LOGIN_PASSWORD}}"
}

> {%
    if (response.status >= 200 && response.status <= 299) {

        const accessToken = response.body.access_token;

        client.global.set("__ACCESS_TOKEN__", accessToken);
        client.global.set("__SESSION_AUTH_HEADER__", `Bearer ${accessToken}`);

        const cookieString = response.headers.valuesOf("Set-Cookie")[0]
        if (cookieString && cookieString.includes("=")) {
            client.global.set("__REFRESH_TOKEN__", cookieString.split(";")[0].split("=")[1]);
        }
    }
%}

### POST Refresh Token
POST {{host}}/api/auth/refresh

> {%
    if (response.status >= 200 && response.status <= 299) {

        const accessToken = response.body.access_token;

        client.global.set("__ACCESS_TOKEN__", accessToken);
        client.global.set("__SESSION_AUTH_HEADER__", `Bearer ${accessToken}`);

        const cookieString = response.headers.valuesOf("Set-Cookie")[0]
        if (cookieString && cookieString.includes("=")) {
            client.global.set("__REFRESH_TOKEN__", cookieString.split(";")[0].split("=")[1]);
        }
    }
%}

### POST Refresh Token
POST {{host}}/api/auth/logout/all
Authorization: {{__SESSION_AUTH_HEADER__}}
