### GET request to example server

GET {{host}}/api/v1/spaces/e7608415-348c-4e69-a43e-ed1c3bea2971/collections
Authorization: {{SESSION_AUTH_HEADER}}
Content-Type: application/json

### GET request to example server

GET {{host}}/api/v1/collections/c040793c-1224-49bc-b75b-74767d2eb351
Authorization: {{SESSION_AUTH_HEADER}}
Content-Type: application/json

