@SPACE_ID = {{__SPACE_ID__}}

### GET request to example server

GET {{host}}/api/v1/spaces
Authorization: {{__SESSION_AUTH_HEADER__}}
Content-Type: application/json

> {%
    client.global.set("__SPACE_ID__", response.body[0].id);
%}

### GET request to example server

GET {{host}}/api/v1/spaces/{{SPACE_ID}}
Authorization: {{__SESSION_AUTH_HEADER__}}
Content-Type: application/json
