### GET request to example server

< _js/auth.js

GET {{host}}/api/v1/spaces
Authorization: {{AUTH_HEADER}}
Accept: application/json

> {%
    client.global.set("SPACE_ID", response.body[0].id);
%}


### GET request to example server

< _js/auth.js

GET {{host}}/api/v1/spaces/{{SPACE_ID}}/collections
Authorization: {{AUTH_HEADER}}
Accept: application/json
