### GET request to example server

< _js/auth.js

GET http://localhost:8080/api/v1/users/me
Authorization: {{AUTH_HEADER}}  # Beispiel: "username:password" base64-codiert
Accept: application/json

###
