/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionTreeDto
 */
export interface CollectionTreeDto {
    /**
     * 
     * @type {string}
     * @memberof CollectionTreeDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionTreeDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionTreeDto
     */
    visibility?: CollectionTreeDtoVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof CollectionTreeDto
     */
    parentId?: string;
    /**
     * 
     * @type {Array<CollectionTreeDto>}
     * @memberof CollectionTreeDto
     */
    children?: Array<CollectionTreeDto>;
}


/**
 * @export
 */
export const CollectionTreeDtoVisibilityEnum = {
    Private: 'PRIVATE',
    Internal: 'INTERNAL',
    Public: 'PUBLIC'
} as const;
export type CollectionTreeDtoVisibilityEnum = typeof CollectionTreeDtoVisibilityEnum[keyof typeof CollectionTreeDtoVisibilityEnum];


/**
 * Check if a given object implements the CollectionTreeDto interface.
 */
export function instanceOfCollectionTreeDto(value: object): value is CollectionTreeDto {
    return true;
}

export function CollectionTreeDtoFromJSON(json: any): CollectionTreeDto {
    return CollectionTreeDtoFromJSONTyped(json, false);
}

export function CollectionTreeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionTreeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(CollectionTreeDtoFromJSON)),
    };
}

export function CollectionTreeDtoToJSON(json: any): CollectionTreeDto {
    return CollectionTreeDtoToJSONTyped(json, false);
}

export function CollectionTreeDtoToJSONTyped(value?: CollectionTreeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'visibility': value['visibility'],
        'parent_id': value['parentId'],
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(CollectionTreeDtoToJSON)),
    };
}

