#@SPACE_ID =

### GET Spaces
GET {{baseUrl}}/v1/spaces
Authorization: Bearer {{accessToken}}

> {%
    if (response.status >= 200 &&
        response.status <= 299 &&
        response.body &&
        response.body.length > 0
    ) {
        const id = response.body[0].id
        client.global.set("SPACE_ID", id);
    }
%}

### GET Space by id
GET {{baseUrl}}/v1/spaces/{{SPACE_ID}}
Authorization: Bearer {{accessToken}}

### GET Collections
GET {{baseUrl}}/v1/spaces/{{SPACE_ID}}/collections
Authorization: Bearer {{accessToken}}

> {%
    if (response.status >= 200 &&
        response.status <= 299 &&
        response.body &&
        response.body.length > 0
    ) {
        const id = response.body[0].id
        client.global.set("COLLECTION_ID", id);
    }
%}

### POST Create collection
POST {{baseUrl}}/v1/spaces/{{SPACE_ID}}/collections
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Another One"
}

> {%
    if (response.status >= 200 &&
        response.status <= 299 &&
        response.body &&
        response.body.length > 0
    ) {
        const id = response.body[0].id
        client.global.set("COLLECTION_ID", id);
    }
%}

### GET Collection by id
GET {{baseUrl}}/v1/collections/{{COLLECTION_ID}}
Authorization: Bearer {{accessToken}}
