@EMAIL=admin@example.com
@PASSWORD=secret123

### POST Sign Up
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "{{EMAIL}}",
  "password": "{{PASSWORD}}"
}

### POST Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{EMAIL}}",
  "password": "{{PASSWORD}}"
}

> {%
    if (response.status >= 200 && response.status <= 299) {
        client.global.set("accessToken", response.body.accessToken);

        const cookieString = response.headers.valuesOf("Set-Cookie")[0]
        if (cookieString && cookieString.includes("=")) {
            client.global.set("refreshToken", cookieString.split(";")[0].split("=")[1]);
        }
    }
%}

### POST Refresh Token
POST {{baseUrl}}/auth/refresh_token

> {%
    if (response.status >= 200 && response.status <= 299) {
        client.global.set("accessToken", response.body.accessToken);

        const cookieString = response.headers.valuesOf("Set-Cookie")[0]
        if (cookieString && cookieString.includes("=")) {
            client.global.set("refreshToken", cookieString.split(";")[0].split("=")[1]);
        }
    }
%}
