spring:
  application:
    name: ragbag-server

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  jwt:
    secret: ${JWT_SECRET}
