spring:
  application:
    name: ragbag-server

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  #packages-to-scan: de.serbroda.ragbag.generated
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs/swagger-ui

security:
  jwt:
    issuer: ragbag
    secret: "CHANGE_ME_TO_A_VERY_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS" # openssl rand -base64 32
    expiration:
      accessToken: 15 # minutes
      refreshToken: 20160 # minutes (14 days)
  api-keys:
    - qixG+XyASUrmrSae1vuMbpe4UjfVaYplU2E3LrqML3Q=
