spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Workspace/ragbag/data/ragbag-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
